services:
  jydn-panel:
    image: ghcr.io/zhiwen1987/jydn-panel:dev
    container_name: jydn-panel
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8008:8008"
    restart: unless-stopped
